### ISSUE TITLE
[Repeating testimonials]

### ISSUE THREAD

**Issue by Nakamcode** [unclebay143/learnease#15]
The testimonial card is repeating it self with the same testimony;

**Comment by unclebay143** [comment]
Hi @Nakamcode,  #17 fixed this, it's on prod now.

Ps: The project website is not fully public at this time [wip].

**Comment by unclebay143** [comment]
Hi @Nakamcode,  #17 fixed this, it's on prod now.

Ps: The project website is not fully public at this time [wip].
