### ISSUE TITLE
[Feature][The website doesn't have an open graph image;]

### ISSUE THREAD

**Issue by Nakamcode** [unclebay143/learnease#16]
### What is an open graph image?

An Open Graph image is a type of metadata that is used to optimize how your website appears on social media platforms like Facebook, Twitter, and LinkedIn. It is a thumbnail image that is displayed alongside the title and description of your website when it is shared on social media.

### Why you should add an open graph image?

Having an Open Graph image is important because it can significantly impact the success of your website on social media platforms. It can improve your website's visibility and engagement by providing a visually appealing thumbnail that encourages people to click through to your website.

**Here's a website to check for open graph images:**

[opengraph.xyz](https://www.opengraph.xyz/)

**Comment by unclebay143** [comment]
There's a designer working on this. Will update once it's ready.

**Comment by Nakamcode** [comment]
Alright;

**Comment by unclebay143** [comment]
Og image added now. #23 
![image](https://user-images.githubusercontent.com/58919619/233741965-27bc4504-ca08-47ec-9586-662d3dedecad.png)

**Comment by Nakamcode** [comment]
Looking Good 😋
